[WIP] Basic string operations
wotpp/wotpp pull request #41
Opened 2021-02-15 17:22 UTC by violetastcs

Implements basic operations that would be useful for a macro language.

(WIP, so far only implemented `slice`)

2021-02-15 21:28 UTC, violetastcs commented
Should be ready for review now.

2021-02-16 02:02 UTC, Jackojc requested changes

2021-02-16 14:51 UTC, Jackojc approved these changes, later dismissed
Good stuff

2021-02-16 14:53 UTC, Jackojc approved these changes
Resolved merge conflicts

2021-02-16 14:53 UTC, merged